### PR TITLE
Implement the initial version of the application

### PR DESCRIPTION
**Pull request by settermjd**
This PR contains the complete working source code of the initial version of the application. While it doesn't contain tests, through manual verification, the code, when properly configured, does work.

### CODE REVIEW

**Comment by pkamp3** [comment]
@bnb Let's take a look in our meeting (I can't add reviewer requests)

**Comment by bnb** [comment]
@settermjd if you could provide screenshots or a link to a running version of the HTML page that's included here, that'd be helpful!

**Comment by settermjd** [comment]
> @settermjd if you could provide screenshots or a link to a running version of the HTML page that's included here, that'd be helpful!

Done!

**Comment by pkamp3** [comment]
Thanks @settermjd !

**Pull request merged**
